[[redirects]]
  from = "/arquivos"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/qr-secreto"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/link-secreto"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/esteganografia"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/termos"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/termos-de-uso"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/*"

  [headers.values]
    Access-Control-Allow-Origin = "https://www.xn--criptovu-h1a.com"
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; connect-src 'self'; font-src 'self'; form-action 'self'; frame-ancestors 'none'; frame-src 'self' blob:; img-src 'self' data: blob:; manifest-src 'self'; media-src 'self' blob:; object-src 'none'; script-src 'self'; script-src-attr 'none'; style-src 'self'; style-src-attr 'none'; worker-src 'self' blob:; require-trusted-types-for 'script'; upgrade-insecure-requests; block-all-mixed-content"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Origin-Agent-Cluster = "?1"
    Permissions-Policy = "accelerometer=(), autoplay=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), hid=(), idle-detection=(), magnetometer=(), microphone=(), midi=(), payment=(), publickey-credentials-get=(), serial=(), usb=(), web-share=(), xr-spatial-tracking=()"
    Referrer-Policy = "no-referrer"
    Vary = "Origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-DNS-Prefetch-Control = "off"
    X-Download-Options = "noopen"
    X-Frame-Options = "DENY"
    X-Permitted-Cross-Domain-Policies = "none"
    X-XSS-Protection = "0"

[[headers]]
  for = "/"

  [headers.values]
    Cache-Control = "private, no-cache, no-store, max-age=0, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/index.html"

  [headers.values]
    Cache-Control = "private, no-cache, no-store, max-age=0, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/assets/*"

  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

